(function c21Admin(){
"use strict";
const data=window.PENGUIN_CONVEXITY_C21_ADMIN;if(!data||data.schemaVersion!=="c2.1-admin-snapshot-v1")return;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),fmt=v=>v==null?"--":new Intl.NumberFormat("zh-CN",{maximumFractionDigits:2,notation:Math.abs(Number(v))>=1000000?"compact":"standard"}).format(v),time=v=>v?new Intl.DateTimeFormat("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(v)):"尚无";
const page=location.pathname.split("/").pop(),host=document.querySelector("main")||document.querySelector(".content")||document.body;
const panel=document.createElement("section");panel.className="c21-admin";panel.id="c21AdminPanel";const updateHero=page==="new-token-update.html"?document.querySelector(".new-token-update-hero"):null;if(updateHero)updateHero.insertAdjacentElement("afterend",panel);else host.insertBefore(panel,host.firstChild);
const stats=(rows)=>`<div class="c21-admin-grid">${rows.map(([k,v])=>`<div class="c21-admin-stat"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join("")}</div>`;
const header=(title,note)=>`<div class="c21-admin-head"><div><span class="c21-kicker">90天新币筛选</span><h2>${esc(title)}</h2><p>${esc(note)}</p></div><span class="c21-time">快照 ${esc(time(data.generatedAt))}</span></div>`;
const table=(heads,rows)=>`<table><thead><tr>${heads.map(x=>`<th>${esc(x)}</th>`).join("")}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join("")}</tr>`).join("")||`<tr><td colspan="${heads.length}">当前没有记录</td></tr>`}</tbody></table>`;
const sourceMeta={coingecko_new_pools:["项目发现","新池与新币发现"],dexscreener:["市场与流动性","公开市场、成交与流动性"],standard_sell_quote:["卖出能力","100美元标准卖出报价"],c2_1_path4:["池与供应历史","已索引池OHLCV与历史供应"],goplus:["安全与供应","显性交易风险与当前供应"],project_website_identity:["身份与产品证据","项目网站与官方仓库链路"],github:["身份与产品证据","官方代码仓库证据"]};
const sourceStateLabel={success:"成功",no_data:"没有返回数据",quota_limited:"额度暂时受限",source_failure:"来源连接失败",unsupported:"当前不支持",configuration_missing:"配置缺失",program_failure:"程序错误"};
const retryableStates=new Set(["source_failure","quota_limited"]),problemStates=new Set(["source_failure","quota_limited","configuration_missing","program_failure"]);
function groupedSourceHealth(){const groups=new Map;for(const row of data.sourceHealth||[]){if(!sourceMeta[row.source_id])continue;if(!groups.has(row.source_id))groups.set(row.source_id,[]);groups.get(row.source_id).push(row)}return [...groups.entries()].map(([sourceId,rows])=>{const counts={};for(const row of rows)counts[row.status]=(counts[row.status]||0)+1;const lastSuccess=rows.map(x=>x.last_success_at).filter(Boolean).sort().at(-1)||null;return{sourceId,rows,counts,lastSuccess,retryable:rows.some(x=>retryableStates.has(x.status)),problems:rows.filter(x=>problemStates.has(x.status)).length,affected:rows.reduce((sum,x)=>sum+Number(x.affected_object_count||0),0)}})}
function sourceHealthCards(){const groups=groupedSourceHealth();return `<div class="c21-source-head"><div><h3>分类更新状态</h3><p>“没有返回数据”和“当前不支持”不是程序错误；可恢复的来源失败和额度受限可以单独更新。</p></div></div><div class="c21-source-grid">${groups.map(group=>{const meta=sourceMeta[group.sourceId],states=Object.entries(group.counts).map(([state,count])=>`<span class="c21-source-state is-${esc(state)}">${esc(sourceStateLabel[state]||state)} ${fmt(count)}</span>`).join("");return `<article class="c21-source-card ${group.problems?"has-problem":""}"><span class="c21-source-category">${esc(meta[0])}</span><h4>${esc(meta[1])}</h4><div class="c21-source-states">${states}</div><small>影响记录 ${fmt(group.affected)} · 最后成功 ${esc(time(group.lastSuccess))}</small>${group.retryable?`<button class="c21-button" type="button" data-c21-retry-source="${esc(group.sourceId)}">单独更新这项</button>`:""}</article>`}).join("")}</div><p class="c21-source-note">配置缺失和程序错误需要先补配置或修复程序，因此不提供无效的重复点击；具体范围和原始原因仍保留在“信源目录”。</p>`}
function overview(){panel.innerHTML=header("90天新币筛选运行概览","这里维护数据、任务和规则；前台只展示判断与边界。")+stats([["Gate 0候选",fmt(data.coverageSummary.discoveredCount)],["90天疑似对象",fmt(data.coverageSummary.suspectedWithin90DaysCount)],["前台项目",fmt(data.coverageSummary.frontVisibleCount)],["T0已核验",fmt(data.coverageSummary.t0VerifiedCount)]])+`<p>当前主库模式：<strong>${esc(data.database.mainDatabaseMode)}</strong>；本版独立写入库：<strong>${esc(data.database.path)}</strong>。</p>`}
async function updateCenter(){panel.innerHTML=header("90天新币筛选","筛选0—90天内有可验证公开流通证据的新币；A/B/C分开表达，不把老项目新资产误叫成新项目。")+`<div id="c21Runtime">正在读取运行状态……</div><div class="c21-admin-actions"><button class="c21-button is-primary" id="c21Run">更新90天新币筛选</button><select id="c21Mode"><option value="manual">仅手动</option><option value="1">每小时</option><option value="3">每3小时</option><option value="6">每6小时</option><option value="12">每12小时</option><option value="24">每天</option></select><button class="c21-button" id="c21PauseAuto">暂停自动更新</button><button class="c21-button" id="c21PauseCurrent">暂停当前任务</button></div><p id="c21ActionFeedback" class="c21-action-feedback" aria-live="polite"></p><p class="c21-source-note">手动和自动调用同一条隐藏、单实例、可恢复流水线，桌面黑框为0。离开页面不会中断任务；关机后在下次Windows登录时从已提交断点恢复。<span id="c21Migration">正在核验正式调度入口。</span></p>${sourceHealthCards()}`;
const runtime=document.querySelector("#c21Runtime"),mode=document.querySelector("#c21Mode"),pauseAuto=document.querySelector("#c21PauseAuto"),actionFeedback=document.querySelector("#c21ActionFeedback");let observedRunning=false;
async function load(){try{const r=await fetch("/api/c2.1/status",{cache:"no-store"}),x=await r.json(),p=x.pipeline||{},c=x.config||{},done=Number(p.completedUnits||0),total=Number(p.totalUnits||0),percent=total?Math.min(100,done/total*100):p.state==="completed"?100:0,message=String(p.message||"").replace(/C2\.1本轮/g,"本轮").replace(/C2\.1/g,"本版"),problemSources=groupedSourceHealth().filter(group=>group.problems).length,stateText={running:"正在运行",completed:problemSources?"处理完成，仍有来源未完成":"本轮全部完成",failed:"程序运行失败",paused:"已暂停",not_started:"尚未运行"}[p.state]||p.state||"未开始",sourceText=problemSources?`${problemSources}类来源未完成`:"来源状态正常";runtime.innerHTML=stats([["任务状态",stateText],["来源状态",sourceText],["当前阶段",p.stage||"--"],["最近完成",time(p.finishedAt)]])+`<p>${esc(message)}</p><div class="c21-progress"><span style="width:${percent}%"></span></div>`;mode.value=c.mode==="automatic"?String(c.intervalHours):"manual";pauseAuto.textContent=c.paused?"恢复自动更新":"暂停自动更新";pauseAuto.dataset.paused=String(!!c.paused);document.querySelector("#c21Migration").textContent=x.existingTaskMigration==="released_same_task"?"现有正式任务已迁移到本版统一更新入口。":"正式调度入口尚未完成发布迁移。";if(p.state==="running")observedRunning=true;else if(observedRunning&&["completed","failed","paused"].includes(p.state)){location.reload();return}}catch(e){runtime.textContent="运行状态暂时读取失败："+e.message}}
async function post(url,payload){const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),x=await r.json();if(!r.ok)throw new Error(x.error||"操作失败");return x}
async function startUpdate(payload,label){actionFeedback.textContent=`正在启动：${label}……`;try{const result=await post("/api/c2.1/run",payload);actionFeedback.textContent=result.message||`${label}已在隐藏后台启动。`;await load()}catch(error){actionFeedback.textContent=`未能启动：${error.message}`}}
document.querySelector("#c21Run").onclick=()=>startUpdate({action:"all"},"90天新币筛选");document.querySelectorAll("[data-c21-retry-source]").forEach(button=>button.onclick=()=>startUpdate({action:"retry_source",sourceId:button.dataset.c21RetrySource},button.closest("article").querySelector("h4").textContent));mode.onchange=async()=>{const manual=mode.value==="manual";await post("/api/c2.1/scheduler",{mode:manual?"manual":"automatic",intervalHours:manual?null:Number(mode.value)});await load()};pauseAuto.onclick=async()=>{await post("/api/c2.1/scheduler",{paused:pauseAuto.dataset.paused!=="true"});await load()};document.querySelector("#c21PauseCurrent").onclick=async()=>{await post("/api/c2.1/pause-current",{paused:true});await load()};await load();setInterval(load,5000)}
function pool(){panel.innerHTML=header("90天候选与宽硬门槛漏斗","D类只在后台保留；A/B/C只有通过全部硬门槛才进入前台。")+stats(Object.entries(data.funnel||{}).map(([k,v])=>[k,fmt(v)]))+table(["关系类别","数量","前台边界"],Object.entries(data.relationshipCounts||{}).map(([k,v])=>[esc(k),fmt(v),k==="D"?"只在后台":"满足硬门槛后可见"]))+`<h3>主要阻断</h3>`+table(["检查码","对象数"],Object.entries(data.quality?.blockerCounts||{}).sort((a,b)=>b[1]-a[1]).map(([k,v])=>[esc(k),fmt(v)]))}
function discovery(){const s=data.supportedScope||{};panel.innerHTML=header("接入范围与可能漏项","范围说明不能缩写成“全市场”。")+stats([["接入链",(s.chains||[]).length],["登记DEX协议",(s.dexProtocols||[]).length],["发现来源",(s.discoverySources||[]).length],["历史来源",(s.historySources||[]).length]])+`<h3>接入链</h3><p>${esc((s.chains||[]).join("、"))}</p><h3>不支持或存在边界</h3><ul>${(s.unsupportedNotes||[]).map(x=>`<li>${esc(typeof x==="string"?x:JSON.stringify(x))}</li>`).join("")||"<li>当前快照没有新增边界项。</li>"}</ul>`}
function sources(){panel.innerHTML=header("来源状态与失败影响","无数据、额度、来源失败、不支持、配置缺失和程序错误分别显示。")+table(["来源","范围","状态","原因","影响对象","最后成功"],(data.sourceHealth||[]).map(x=>[esc(x.source_id),esc(x.scope_key),esc(x.status),esc(x.plain_reason||x.reason_code),fmt(x.affected_object_count),esc(time(x.last_success_at))]))}
function backbone(){panel.innerHTML=header("独立数据主干与恢复点","页面始终读取最后一份完整快照，不读取写入中的中间表。")+stats([["写入数据库",data.database.path],["主库",data.database.mainDatabaseMode],["来源游标",(data.cursors||[]).length],["快照构建",(data.snapshotBuilds||[]).length]])+table(["来源","范围","阶段","状态","更新时间"],(data.cursors||[]).slice(0,60).map(x=>[esc(x.source_id),esc(x.scope_key),esc(x.stage),esc(x.status),esc(time(x.updated_at))]))}
function rules(){const r=data.ruleSummary||{};panel.innerHTML=header("冻结规则与回放入口","总分只排序；四路径、五状态和防抖按需求锁计算。")+stats([["规则版本",data.ruleVersion],["年龄权重","0"],["强路径",Object.keys(r.strongPaths||{}).length],["五状态",(r.statePriority||[]).length]])+table(["优先级","状态"],(r.statePriority||[]).map((x,i)=>[String(i+1),esc(x)]))+`<p><strong>防抖：</strong>${esc(JSON.stringify(r.hysteresis||{}))}</p>`}
function quality(){panel.innerHTML=header("五因子方向与独立可信度","方向与可信度独立于前台资格；缺失字段不补0、不跨因子重分配。")+stats(Object.entries(data.quality?.confidenceLevels||{}).map(([k,v])=>[k,fmt(v)]))+table(["因子方向","出现次数"],Object.entries(data.quality?.factorDirections||{}).map(([k,v])=>[esc(k),fmt(v)]))}
({"workbench.html":overview,"new-token-update.html":updateCenter,"project-master-pool.html":pool,"source-discovery.html":discovery,"source-registry.html":sources,"data-backbone.html":backbone,"rules-replay.html":rules,"decision-quality.html":quality}[page]||overview)();
})();
