(function c22Admin(){
"use strict";
const data=window.PENGUIN_CONVEXITY_C22_ADMIN;if(!data||data.schemaVersion!=="c2.2-admin-v1")return;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),fmt=v=>v==null?"--":new Intl.NumberFormat("zh-CN",{maximumFractionDigits:2,notation:Math.abs(Number(v))>=1000000?"compact":"standard"}).format(v),time=v=>v?new Intl.DateTimeFormat("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(v)):"尚无";
const page=location.pathname.split("/").pop(),host=document.querySelector("main")||document.body;
const old=document.querySelector("#c21AdminPanel");if(old)old.remove();
const panel=document.createElement("section");panel.className="c21-admin c22-admin";panel.id="c22AdminPanel";
const screening=data.screening||{},tracking=data.tracking||{},jobs=data.jobs||{};
function stats(rows){return`<div class="c21-admin-grid">${rows.map(([k,v])=>`<div class="c21-admin-stat"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join("")}</div>`}
function sourceRows(){const rows=(data.sourceHealth||[]).filter(x=>x.status&&x.status!=="healthy"&&x.status!=="success").slice(0,12);return rows.length?`<details class="c22-source-details"><summary>后台来源异常 ${rows.length} 条（前台不显示为项目状态）</summary><table><thead><tr><th>来源</th><th>状态</th><th>原因</th><th>影响对象</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.source_id)}</td><td>${esc(x.status)}</td><td>${esc(x.plain_reason||x.reason_code||"未说明")}</td><td>${esc(x.affected_object_count||0)}</td></tr>`).join("")}</tbody></table></details>`:`<p class="c21-source-note">当前快照没有需要单独展示的来源异常。</p>`}
function job(jobCode){const j=jobs[jobCode]||{};return`<div class="c22-job"><div><strong>${esc(jobCode==="screening"?"新币筛选":"凸性跟踪")}</strong><span>${esc(j.state||"未开始")}</span></div><small>阶段：${esc(j.stage||"--")} · 最近完成：${esc(time(j.lastCompletedAt))}</small></div>`}
function header(title,note){return`<div class="c21-admin-head"><div><span class="c21-kicker">C2.2 更新中心</span><h2>${esc(title)}</h2><p>${esc(note)}</p></div><span class="c21-time">快照 ${esc(time(data.generatedAt))}</span></div>`}
function scheduleControls(jobCode){const configJob=(data.config?.jobs||{})[jobCode]||{},mode=configJob.mode||"automatic",interval=Number(configJob.intervalHours||24);return`<div class="c22-schedule-controls" data-c22-job="${jobCode}"><label>更新方式<select id="c22Mode"><option value="automatic" ${mode==="automatic"?"selected":""}>自动</option><option value="manual" ${mode==="manual"?"selected":""}>仅手动</option></select></label><label>自动频率<select id="c22Interval"><option value="1" ${interval===1?"selected":""}>每1小时</option><option value="3" ${interval===3?"selected":""}>每3小时</option><option value="6" ${interval===6?"selected":""}>每6小时</option><option value="12" ${interval===12?"selected":""}>每12小时</option><option value="24" ${interval===24?"selected":""}>每天</option></select></label><button class="c21-button" id="c22SaveSchedule">保存本页设置</button></div>`}
function screeningPage(){const c=screening.coverageSummary||{};panel.innerHTML=header("新币筛选更新","这里仅负责90天新币第一关：发现、T0、A/B/C、宽硬门槛和产品证据。凸性跟踪在另一页独立更新。")+stats([["筛选候选",fmt(screening.candidateCount)], ["T0已核验",fmt(c.t0VerifiedCount)], ["通过硬门槛",fmt(c.hardGatePassedCount)], ["当前前台",fmt(c.frontVisibleCount)]])+`<div class="c22-job-grid">${job("screening")}${job("convexity_tracking")}</div><div class="c21-admin-actions"><button class="c21-button is-primary" id="c22ScreeningRun">更新新币筛选</button><button class="c21-button" id="c22ScreeningPause">暂停当前任务</button></div>${scheduleControls("screening")}<p id="c22Feedback" class="c21-action-feedback" aria-live="polite"></p>${sourceRows()}`;bind("screening","更新新币筛选")}
function trackingPage(){const count=tracking.items?.length||0;panel.innerHTML=header("凸性跟踪更新","这里仅负责第二关：交易、流动性、供应、产品使用、风险、四条强路径和动态后验。新币筛选在另一页独立更新。")+stats([["候选输入",fmt(count)], ["凸性线索",fmt(tracking.stateCounts?.convexity_clue)], ["活跃项目",fmt(tracking.stateCounts?.active_project)], ["观察中",fmt(tracking.stateCounts?.observing)]])+`<div class="c22-job-grid">${job("convexity_tracking")}${job("screening")}</div><div class="c21-admin-actions"><button class="c21-button is-primary" id="c22TrackingRun">更新凸性跟踪</button><button class="c21-button" id="c22TrackingPause">暂停当前任务</button></div>${scheduleControls("convexity_tracking")}<p id="c22Feedback" class="c21-action-feedback" aria-live="polite"></p>${sourceRows()}`;bind("convexity_tracking","更新凸性跟踪")}
function calibrationBlock(){const summary=data.calibration?.summary||{};return`<section class="c22-calibration"><h3>时间外校准（只读）</h3><p>不调权、不调门槛、不改变项目状态；少于30个真实结果只显示样本不足。</p><div class="c22-calibration-grid">${[7,14,30].map(h=>{const row=summary[String(h)]||{};return`<div><strong>${h}天</strong><span>${esc(row.sampleStatus==="sample_insufficient"?"样本不足":row.sampleStatus||"未生成")}</span><small>可用结果 ${esc(row.availableCount??0)}</small></div>`}).join("")}</div></section>`}
function overview(){const c=screening.coverageSummary||{};panel.innerHTML=header("C2.2 主干运行概览","同一个产品、两个独立作业、一个可恢复调度入口。筛选和跟踪各自保存完整快照，失败不互相覆盖。")+stats([["当前前台",fmt(c.frontVisibleCount)], ["筛选候选",fmt(screening.candidateCount)], ["跟踪记录",fmt(tracking.items?.length)], ["来源记录",fmt((data.sourceHealth||[]).length)]])+`<div class="c22-job-grid">${job("screening")}${job("convexity_tracking")}</div>${calibrationBlock()}${sourceRows()}`}
function bind(jobCode,label){const button=document.querySelector(jobCode==="screening"?"#c22ScreeningRun":"#c22TrackingRun"),pause=document.querySelector(jobCode==="screening"?"#c22ScreeningPause":"#c22TrackingPause"),save=document.querySelector("#c22SaveSchedule"),mode=document.querySelector("#c22Mode"),interval=document.querySelector("#c22Interval"),feedback=document.querySelector("#c22Feedback");if(button)button.onclick=async()=>{feedback.textContent=`正在启动：${label}……`;try{const r=await fetch("/api/c2.2/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobCode,trigger:"manual"})});const x=await r.json();if(!r.ok)throw new Error(x.error||"启动失败");feedback.textContent=x.message||`${label}已在隐藏后台启动。`}catch(e){feedback.textContent=`未能启动：${e.message}`}};if(pause)pause.onclick=async()=>{feedback.textContent="正在请求暂停当前任务……";try{const r=await fetch("/api/c2.2/pause-current",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({paused:true})});const x=await r.json();if(!r.ok)throw new Error(x.error||"暂停失败");feedback.textContent=x.message||"已记录暂停请求。"}catch(e){feedback.textContent=`未能暂停：${e.message}`}};if(save)save.onclick=async()=>{feedback.textContent="正在保存本页更新设置……";try{const r=await fetch("/api/c2.2/scheduler",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobCode,mode:mode.value,intervalHours:mode.value==="manual"?null:Number(interval.value)})});const x=await r.json();if(!r.ok)throw new Error(x.error||"设置保存失败");feedback.textContent="本页更新设置已保存；另一页设置不受影响。"}catch(e){feedback.textContent=`设置未保存：${e.message}`}};if(mode)mode.onchange=()=>{interval.disabled=mode.value==="manual"}}
function collapseLegacyTrackingPage(){
 if(page!=="update-center.html")return;
 const legacy=[...host.children].filter(node=>node!==panel);
 if(!legacy.length)return;
 const details=document.createElement("details");details.className="c22-legacy-details";
 details.innerHTML="<summary>展开继承的凸性工作台明细与单项重试</summary>";
 legacy.forEach(node=>details.appendChild(node));
 host.appendChild(details);
}
if(page==="new-token-update.html"){
 const hero=document.querySelector(".new-token-update-hero");if(hero)hero.insertAdjacentElement("afterend",panel);else host.insertBefore(panel,host.firstChild);screeningPage();
}else if(page==="update-center.html"){
 host.insertBefore(panel,host.firstChild);trackingPage();collapseLegacyTrackingPage();
}else{host.insertBefore(panel,host.firstChild);overview()}
})();
